#Test php5.6 and php7.0
language: php
php:
  - 5.6
  - 7.0
#RequireDB
env:
  - DB=mysql
#Allow errors in php7
matrix:
  allow_failures:
    - php: 7.0
#Create Database
before_script:
  - mysql -e 'create database RPICMS;'
#RunTests
script: phpunit --configuration phpunit_$DB.xml --coverage-text
